[package]
name = "vault-zk-risc0"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
bincode.workspace = true
incrementalmerkletree.workspace = true
orchard.workspace = true
pasta_curves.workspace = true
rand_chacha.workspace = true
risc0-zkvm = { workspace = true, features = ["prove", "disable-dev-mode"] }
thiserror.workspace = true
vault-burn = { path = "../../../crates/vault-burn" }
vault-privacy = { path = "../../../crates/vault-privacy" }
vault-protocol = { path = "../../../crates/vault-protocol" }
vault-zk-transfer-core = { path = "../core" }
vault-zk-transfer-methods = { path = "../methods" }

[lints]
workspace = true
